spring:
    http:
        encoding:
            charset: UTF-8
    # h2:
    #     console:
    #         enabled: true
    #         path: /h2
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
        # static-path-pattern: /static/**
    output:
        ansi:
            enabled: always
    servlet:
        multipart:
            max-file-size: 128MB
            max-request-size: 128MB
    resources:
        static-locations:
            - classpath:/static/
        add-mappings: true
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
        username: root
        password: 1234
        
        
## 서버 운영 환경
server:
    servlet:
        context-path: /
        session: 
            timeout: 60
    tomcat:
        uri-encoding: UTF-8
    port: 8080
## database 설정
